export const API_ENDPOINTS = {
  authLogin: "/api/v1/auth/login",
  authSwitchContext: "/api/v1/auth/switch-context",
  authSession: "/api/v1/auth/session",
  executiveSummary: "/api/v1/dashboard/executive-summary",
  newsFeed: "/api/v1/news-feed",
  newsFeedChannels: "/api/v1/news-feed/channels",
  companies: "/api/v1/companies",
  tenantCompanies: "/api/v1/tenant/companies",
  tenantCompany: (companyId: string) => `/api/v1/tenant/companies/${companyId}`,
  platformTenants: "/api/v1/platform/tenants",
  platformTenantsBulkLifecycle: "/api/v1/platform/tenants/bulk-lifecycle",
  platformTenant: (tenantId: string) => `/api/v1/platform/tenants/${tenantId}`,
  platformTenantCompanies: (tenantId: string) => `/api/v1/platform/tenants/${tenantId}/companies`,
  platformTenantOwner: (tenantId: string) => `/api/v1/platform/tenants/${tenantId}/owner`,
  platformTenantMemberships: (tenantId: string) => `/api/v1/platform/tenants/${tenantId}/memberships`,
  platformHealth: "/api/v1/platform/health",
  platformAuditEvents: "/api/v1/platform/audit-events",
  tenantAuditEvents: "/api/v1/tenant/audit-events",
  issues: "/api/v1/issues",
  issueById: (issueId: string) => `/api/v1/issues/${issueId}`,
  articleSource: (articleId: string) => `/api/v1/articles/${articleId}/source`,
  savedIssues: "/api/v1/saved/issues",
  issueSaved: (issueId: string) => `/api/v1/issues/${issueId}/saved`,
  issueSavedStatus: (issueId: string) => `/api/v1/issues/${issueId}/saved`,
  issueComplete: (issueId: string) => `/api/v1/issues/${issueId}/complete`,
  inboxEmails: "/api/v1/inbox/emails",
  inboxEmailRead: (emailId: string) => `/api/v1/inbox/emails/${emailId}/read`,
  companyContext: (companyId: string) => `/api/v1/companies/${companyId}/context`,
  companyContextVersions: (companyId: string) => `/api/v1/companies/${companyId}/context/versions`,
  companyContextIdentityRetry: (companyId: string) => `/api/v1/companies/${companyId}/context/management-identity/retry`,
  companyContextDraft: "/api/v1/company-context/draft",
  companyContextPdfDraft: "/api/v1/company-context/draft/pdf",
  companyContextDraftById: (draftId: string) => `/api/v1/company-context/drafts/${draftId}`,
  companyContextDraftReview: (draftId: string) => `/api/v1/company-context/drafts/${draftId}/submit-review`,
  companyContextDraftApprove: (draftId: string) => `/api/v1/company-context/drafts/${draftId}/approve`,
  alertPreference: (companyId: string) => `/api/v1/companies/${companyId}/alert-preference`,
  alertPreferenceRead: (companyId: string) => `/api/v1/companies/${companyId}/alert-preference`,
  languagePreference: (companyId: string) => `/api/v1/companies/${companyId}/language-preference`,
  languagePreferenceRead: (companyId: string) => `/api/v1/companies/${companyId}/language-preference`,
  newsIntakeStatus: "/api/v1/news-intake/status",
  newsIntakeAutomatic: "/api/v1/news-intake/automatic",
  newsIntakePull: "/api/v1/news-intake/pull",
  newsIntakeRuns: "/api/v1/news-intake/runs",
  reports: "/api/v1/reports",
  reportById: (reportId: string) => `/api/v1/reports/${reportId}`,
  reportPdf: (reportId: string) => `/api/v1/reports/${reportId}/pdf`,
  reportReview: (reportId: string) => `/api/v1/reports/${reportId}/review`,
  reportApprove: (reportId: string) => `/api/v1/reports/${reportId}/approve`,
  reportShare: (reportId: string) => `/api/v1/reports/${reportId}/share`,
  reportNarrativeRewrite: (reportId: string, narrativeId: string) =>
    `/api/v1/reports/${reportId}/narrative/${narrativeId}/rewrite`,
  tenantMemberships: "/api/v1/tenant/memberships",
  tenantMembership: (membershipId: string) => `/api/v1/tenant/memberships/${membershipId}`,
  companyMemberships: "/api/v1/company/memberships",
  companyMembership: (membershipId: string) => `/api/v1/company/memberships/${membershipId}`,
} as const;
