export const API_ENDPOINTS = {
  executiveSummary: "/api/v1/dashboard/executive-summary",
  companies: "/api/v1/companies",
  issues: "/api/v1/issues",
  issueById: (issueId: string) => `/api/v1/issues/${issueId}`,
  articleSource: (articleId: string) => `/api/v1/articles/${articleId}/source`,
  savedIssues: "/api/v1/saved/issues",
  issueSaved: (issueId: string) => `/api/v1/issues/${issueId}/saved`,
  issueComplete: (issueId: string) => `/api/v1/issues/${issueId}/complete`,
  feedback: "/api/v1/feedback",
  inboxEmails: "/api/v1/inbox/emails",
  inboxEmailRead: (emailId: string) => `/api/v1/inbox/emails/${emailId}/read`,
  companyContext: (companyId: string) => `/api/v1/companies/${companyId}/context`,
  companyContextDraft: "/api/v1/company-context/draft",
  companyContextDraftById: (draftId: string) => `/api/v1/company-context/drafts/${draftId}`,
  companyContextDraftReview: (draftId: string) => `/api/v1/company-context/drafts/${draftId}/submit-review`,
  companyContextDraftApprove: (draftId: string) => `/api/v1/company-context/drafts/${draftId}/approve`,
  alertPreference: (companyId: string) => `/api/v1/companies/${companyId}/alert-preference`,
  alertPreferenceRead: (companyId: string) => `/api/v1/companies/${companyId}/alert-preference`,
  reports: "/api/v1/reports",
  reportById: (reportId: string) => `/api/v1/reports/${reportId}`,
  reportReview: (reportId: string) => `/api/v1/reports/${reportId}/review`,
  reportApprove: (reportId: string) => `/api/v1/reports/${reportId}/approve`,
  reportShare: (reportId: string) => `/api/v1/reports/${reportId}/share`,
  reportNarrativeRewrite: (reportId: string, narrativeId: string) =>
    `/api/v1/reports/${reportId}/narrative/${narrativeId}/rewrite`,
} as const;
